### ISSUE TITLE
RT hydro

### ISSUE THREAD

**Issue by kibaekkim** [GridMod/RTS-GMLC#22]
There is no hydro data for RT.

**Comment by oconnellm** [comment]
The hydro generation is passed to the RT from the DA run with the "Pass Fixed Load" data file and the "RT Run" scenario.

**Comment by kibaekkim** [comment]
@oconnellm Thanks for the answer. Does that mean the RT hydro data is available only inside PLEXOS? Can we have the RT data in cvs files?

**Comment by oconnellm** [comment]
To expand on the previous comment...

The hydro generation profiles are fixed in the DA runs. This fixed generation profile is also used in the RT run, but instead of using the same input data file (you can't because the RT run is 5 minute interval while the DA is hourly) you must pass the DA hydro generation values to the RT run. So the RT run is still using the same generation profile as the DA run, just not accessing it through the same data file.

**Comment by oconnellm** [comment]
@kibaekkim the RT hydro data is only available as an output from PLEXOS. We input hourly generation data and it converts that to 5 minute generation to match the energy from the hourly generation data. (by ramping up and then down to achieve the same energy generated)

**Comment by kibaekkim** [comment]
@oconnellm Does that mean the hydro generation is controllable for 5-minute interval dispatch for fixed hourly dispatch?

**Comment by oconnellm** [comment]
@kibaekkim No. The 5-minute dispatch is also fixed.

**Comment by kibaekkim** [comment]
@oconnellm Is there any hope that PLEXOS can export the 5-minute hydro dispatch to a file so that non-PLEXOS users can use it?
