### ISSUE TITLE
how to use the reserve data?

### ISSUE THREAD

**Issue by kibaekkim** [GridMod/RTS-GMLC#32]
Could you please explain how the reserve data can be used in the model? Is this the system-wide reserve amount? What is the value of the data?

**Comment by claytonpbarrows** [comment]
The [reserves profiles](https://github.com/GridMod/RTS-GMLC/tree/master/RTS_Data/timeseries_data_files/reserves) are all in MW. The PLEXOS model uses the profiles to inform the system wide reserve holding requirement in the different scheduling problems. 
We have also included a spinning reserve requirement in each region equal to 3% regional load. 

The requirements for each of the 5 (3 up and 2 down) reserve products that are included in the PLEXOS model are outlined [here](https://github.com/GridMod/RTS-GMLC/blob/master/Create_PLEXOS_database/1-parse-matpower/outputs/reserve.data.csv). The `VORS` is the cost of not procuring the reserve requirement. The `timeframe` value describes the response time constraint for capacity held to meet the reserve requirement. i.e. if the reserve retirement is 10 MW and the response time s 600s, the solution would be required to hold enough committed capacity so that it could supply an additional 10MW of generation within 10 minutes.
It's worth noting that the PLEXOS model doesn't simulate the deployment of reserves, just the scheduling of reserve holding.
