### ISSUE TITLE
gen costs: 4th load/cost point and convexity

### ISSUE THREAD

**Issue by krishnakanaparthi** [GridMod/RTS-GMLC#49]
In the RTS.m file, three load/cost points are provided. Could the 4th point for Pmax load and its cost also be provided for the piecewise linear cost function?

Also, is the slightly non-convexity of the slope of the three load/cost points really intended to be or is it emanating from the RTS_96 heat rates itself?

**Comment by claytonpbarrows** [comment]
@krishnakanaparthi In which units do you see a non-convexity?

In the Net_Heat_Rate P-Q pairs, I don't see it:
![image](https://cloud.githubusercontent.com/assets/7231396/24925832/c0b17492-1eb6-11e7-8769-1a16b5cc77bc.png)

I do see what looks like a non-convexity in the Inc_Heat_Rate curves:
![image](https://cloud.githubusercontent.com/assets/7231396/24925871/e418875e-1eb6-11e7-8d71-0808ecce3633.png)

But I don't think that matters since Inc_Heat_Rate only defines the slope between the output points on the curve. 

The RTS.m file has costs in $/hr. When divided by the output points, the curves look like this:
![image](https://cloud.githubusercontent.com/assets/7231396/24926223/2b1c14e4-1eb8-11e7-89fc-1e86d8329b21.png)

**Comment by claytonpbarrows** [comment]
also in the 'reorganize' branch, I've included the 4th point on the heat_rate curve in the reformatted [gen.csv](https://github.com/GridMod/RTS-GMLC/blob/reorganize/RTS_Data/SourceData/gen.csv)

**Comment by krishnakanaparthi** [comment]
@claytonpbarrows, thank you for the detailed plots and explanation.

Yes, I was looking at the slopes of the load/cost points regarding non-convexity. And as you mentioned, there is non-convexity in the Inc_Heat_Rate curves.

The 4th point on the heat_rate curve was what I was looking for. Thank you again.
