### ISSUE TITLE
csp/storage

### ISSUE THREAD

**Issue by rafcastro99** [GridMod/RTS-GMLC#52]
Please clarify the meaning of the data in the following files:
- csp_gens
- csp
- storage.props
Thanks

**Comment by claytonpbarrows** [comment]
@rafcastro99, I reorganized the data so that it is a bit more approachable. The CSP generator and the associated storage facility are now described in [gen.csv](https://github.com/GridMod/RTS-GMLC/blob/master/RTS_Data/SourceData/gen.csv) and [storage.csv](https://github.com/GridMod/RTS-GMLC/blob/master/RTS_Data/SourceData/storage.csv). Please see the [README](https://github.com/GridMod/RTS-GMLC/blob/master/RTS_Data/SourceData/README.md) that describes the data files in [SourceData](https://github.com/GridMod/RTS-GMLC/blob/master/RTS_Data/SourceData) and let me know if more clarification is required.
