### ISSUE TITLE
include RTS.m in MATPOWER distribution

### ISSUE THREAD

**Issue by rdzman** [GridMod/RTS-GMLC#76]
I was just wondering how you would feel about me including the MATPOWER file for this RTS case in the [MATPOWER distribution](https://github.com/MATPOWER/matpower)? I would, of course, be happy to include a link in the help text at the top of the file pointing back to this repository as the original source.

**Comment by claytonpbarrows** [comment]
I think that would be great! It appears as though this repository will remain a bit of a moving target. I think we're at a fairly stable point now. But, going forward there are a number of suggested features and updates that we would like to add. While I think the timeline for most of them is several months out, it would be a good idea to link back to this repo so that users can get updated versions.

**Comment by rdzman** [comment]
Thanks. I'll also try to keep an eye on the updates here so I can incorporate them into the version bundled with MATPOWER.

**Comment by ccoffrin** [comment]
You might consider git submodules.  They can be used to embed one repository inside another.

**Comment by rdzman** [comment]
I prefer using [git-subrepo](https://github.com/ingydotnet/git-subrepo) for that, since it doesn't require everybody using my repo to know anything about how subrepos or submodules work. But, I'm not sure either works if all I want is a single file.
